"""Executive HTML Report Generator with Print CSS and Stored XSS Protection.

Guarantees:
- Zero external CDN or internet dependencies (self-contained inline CSS styles).
- Full XSS protection: every dynamic text field is strictly sanitized with html.escape(quote=True).
- @media print optimization for clean, multi-page paper/PDF exports.
- Prominent compliance disclaimers and clear visual demarcation between Authoritative
  GRC calculations and AI-Assisted Advisory decision support.
- Enforces MAX_REPORT_ROWS ceiling.
"""

import html
from typing import Any, Dict, List, Optional
from datetime import datetime

MAX_REPORT_ROWS = 10000

STANDARD_DISCLAIMER = (
    "DISCLAIMER: This report is generated automatically by the AI-GRC Platform for internal "
    "risk management, vulnerability prioritization, and compliance tracking purposes. It does "
    "not constitute formal legal counsel, regulatory certification, or guarantee of third-party audit attestation."
)


def safe_escape(val: Any) -> str:
    """Escapes user and scanner controlled strings for safe HTML rendering."""
    if val is None:
        return ""
    return html.escape(str(val), quote=True)


def build_html_report(
    title: str,
    subtitle: str,
    summary_cards: List[Dict[str, Any]],
    table_headers: List[str],
    table_rows: List[List[Any]],
    ai_advisories: Optional[List[Dict[str, Any]]] = None,
    generated_by: str = "system",
    generated_at: Optional[datetime] = None,
    disclaimer: str = STANDARD_DISCLAIMER,
) -> str:
    """Renders a self-contained executive HTML report.

    Raises:
        ValueError: If row count exceeds MAX_REPORT_ROWS.
    """
    if len(table_rows) > MAX_REPORT_ROWS:
        raise ValueError(
            f"Report '{title}' query returned {len(table_rows)} rows, exceeding the maximum "
            f"supported export limit of {MAX_REPORT_ROWS} rows. Please apply query filters."
        )

    ts = (generated_at or datetime.utcnow()).strftime("%Y-%m-%d %H:%M:%S UTC")
    escaped_title = safe_escape(title)
    escaped_subtitle = safe_escape(subtitle)
    escaped_author = safe_escape(generated_by)
    escaped_disclaimer = safe_escape(disclaimer)

    # Build KPI Cards HTML
    cards_html = ""
    for card in summary_cards:
        c_label = safe_escape(card.get("label", ""))
        c_val = safe_escape(card.get("value", ""))
        c_sub = safe_escape(card.get("sub", ""))
        c_color = card.get("color", "accent")
        cards_html += f"""
        <div class="kpi-card kpi-{c_color}">
            <div class="kpi-label">{c_label}</div>
            <div class="kpi-value">{c_val}</div>
            {f'<div class="kpi-sub">{c_sub}</div>' if c_sub else ''}
        </div>
        """

    # Build Authoritative Table HTML
    headers_html = "".join(f"<th>{safe_escape(h)}</th>" for h in table_headers)
    rows_html = ""
    for row in table_rows:
        cells_html = "".join(f"<td>{safe_escape(cell)}</td>" for cell in row)
        rows_html += f"<tr>{cells_html}</tr>\n"

    # Build AI Advisory Section HTML (if any)
    ai_section_html = ""
    if ai_advisories:
        ai_cards_html = ""
        for adv in ai_advisories:
            adv_title = safe_escape(adv.get("title", "Advisory Finding"))
            adv_prio = safe_escape(adv.get("priority", "Informational"))
            adv_text = safe_escape(adv.get("simple_explanation", ""))
            adv_rec = safe_escape(adv.get("recommendation", ""))
            ai_cards_html += f"""
            <div class="ai-advisory-item">
                <div class="ai-advisory-header">
                    <span class="ai-badge ai-badge-{adv_prio.lower()}">{adv_prio} Priority</span>
                    <strong>{adv_title}</strong>
                </div>
                <div class="ai-advisory-body">{adv_text}</div>
                {f'<div class="ai-advisory-rec"><strong>Recommendation:</strong> {adv_rec}</div>' if adv_rec else ''}
            </div>
            """

        ai_section_html = f"""
        <section class="section ai-section">
            <div class="section-badge ai-badge-tag">[AI-ASSISTED ADVISORY — NON-AUTHORITATIVE]</div>
            <h2>AI-Assisted Risk & Remediation Decision Support</h2>
            <div class="ai-notice">
                <strong>Notice:</strong> The following insights are generated by automated LLM decision support for human review.
                They are purely advisory, do not alter official GRC risk ratings, and do not constitute compliance certification.
            </div>
            <div class="ai-grid">
                {ai_cards_html}
            </div>
        </section>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{escaped_title} — AI-GRC Platform</title>
    <style>
        :root {{
            --bg-color: #0f172a;
            --surface: #1e293b;
            --surface-border: #334155;
            --text-primary: #f8fafc;
            --text-secondary: #94a3b8;
            --accent: #38bdf8;
            --accent-glow: rgba(56, 189, 248, 0.15);
            --danger: #ef4444;
            --warning: #f59e0b;
            --success: #10b981;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            background: var(--bg-color);
            color: var(--text-primary);
            line-height: 1.5;
            padding: 2.5rem 1.5rem;
        }}
        .report-container {{
            max-width: 1200px;
            margin: 0 auto;
        }}
        .header {{
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            border-bottom: 2px solid var(--surface-border);
            padding-bottom: 1.5rem;
            margin-bottom: 1.5rem;
        }}
        .header-title h1 {{
            font-size: 1.85rem;
            font-weight: 700;
            color: var(--text-primary);
            letter-spacing: -0.02em;
        }}
        .header-title p {{
            color: var(--text-secondary);
            font-size: 0.95rem;
            margin-top: 0.25rem;
        }}
        .meta-box {{
            text-align: right;
            font-size: 0.85rem;
            color: var(--text-secondary);
        }}
        .meta-box strong {{ color: var(--accent); }}
        .disclaimer-banner {{
            background: rgba(245, 158, 11, 0.1);
            border-left: 4px solid var(--warning);
            padding: 0.85rem 1.25rem;
            margin-bottom: 2rem;
            font-size: 0.85rem;
            color: #fde68a;
            border-radius: 4px;
        }}
        .kpi-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin-bottom: 2.5rem;
        }}
        .kpi-card {{
            background: var(--surface);
            border: 1px solid var(--surface-border);
            border-radius: 8px;
            padding: 1.25rem;
        }}
        .kpi-label {{
            font-size: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-secondary);
            margin-bottom: 0.35rem;
        }}
        .kpi-value {{
            font-size: 1.75rem;
            font-weight: 700;
            color: var(--text-primary);
        }}
        .kpi-sub {{
            font-size: 0.8rem;
            color: var(--text-secondary);
            margin-top: 0.25rem;
        }}
        .kpi-danger .kpi-value {{ color: var(--danger); }}
        .kpi-warning .kpi-value {{ color: var(--warning); }}
        .kpi-success .kpi-value {{ color: var(--success); }}
        .kpi-accent .kpi-value {{ color: var(--accent); }}
        .section {{
            margin-bottom: 3rem;
            position: relative;
        }}
        .section-badge {{
            display: inline-block;
            font-size: 0.7rem;
            font-weight: 700;
            letter-spacing: 0.05em;
            padding: 0.2rem 0.6rem;
            border-radius: 4px;
            margin-bottom: 0.5rem;
            text-transform: uppercase;
        }}
        .badge-auth {{
            background: #0284c7;
            color: #ffffff;
        }}
        .section h2 {{
            font-size: 1.35rem;
            font-weight: 600;
            margin-bottom: 1rem;
            color: var(--text-primary);
        }}
        .table-wrapper {{
            overflow-x: auto;
            border: 1px solid var(--surface-border);
            border-radius: 8px;
            background: var(--surface);
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 0.875rem;
            text-align: left;
        }}
        th {{
            background: #1e293b;
            color: var(--text-secondary);
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.75rem;
            letter-spacing: 0.05em;
            padding: 0.75rem 1rem;
            border-bottom: 1px solid var(--surface-border);
        }}
        td {{
            padding: 0.85rem 1rem;
            border-bottom: 1px solid var(--surface-border);
            color: var(--text-primary);
        }}
        tr:last-child td {{ border-bottom: none; }}
        tr:hover {{ background: rgba(255, 255, 255, 0.02); }}
        .ai-section {{
            background: rgba(30, 41, 59, 0.6);
            border: 1px solid rgba(245, 158, 11, 0.3);
            border-radius: 8px;
            padding: 1.5rem;
        }}
        .ai-badge-tag {{
            background: #f59e0b;
            color: #000000;
        }}
        .ai-notice {{
            font-size: 0.85rem;
            color: #cbd5e1;
            margin-bottom: 1.25rem;
            padding-bottom: 0.75rem;
            border-bottom: 1px solid rgba(245, 158, 11, 0.2);
        }}
        .ai-grid {{
            display: grid;
            gap: 1rem;
        }}
        .ai-advisory-item {{
            background: rgba(15, 23, 42, 0.6);
            border: 1px solid var(--surface-border);
            border-radius: 6px;
            padding: 1rem;
        }}
        .ai-advisory-header {{
            display: flex;
            align-items: center;
            gap: 0.5rem;
            margin-bottom: 0.5rem;
        }}
        .ai-badge {{
            font-size: 0.7rem;
            font-weight: 700;
            padding: 0.15rem 0.5rem;
            border-radius: 4px;
            text-transform: uppercase;
        }}
        .ai-badge-critical {{ background: var(--danger); color: #fff; }}
        .ai-badge-high {{ background: #ea580c; color: #fff; }}
        .ai-badge-medium {{ background: var(--warning); color: #000; }}
        .ai-badge-low {{ background: var(--success); color: #fff; }}
        .ai-advisory-body {{
            font-size: 0.9rem;
            color: #e2e8f0;
            margin-bottom: 0.5rem;
        }}
        .ai-advisory-rec {{
            font-size: 0.85rem;
            color: #94a3b8;
            border-top: 1px dashed var(--surface-border);
            padding-top: 0.5rem;
        }}
        .footer {{
            border-top: 1px solid var(--surface-border);
            padding-top: 1.5rem;
            margin-top: 3rem;
            font-size: 0.8rem;
            color: var(--text-secondary);
            text-align: center;
        }}
        @media print {{
            body {{
                background: #ffffff !important;
                color: #000000 !important;
                padding: 0 !important;
            }}
            .report-container {{ max-width: 100% !important; }}
            .kpi-card, .table-wrapper, .ai-section, .ai-advisory-item {{
                background: #ffffff !important;
                border: 1px solid #cccccc !important;
                color: #000000 !important;
            }}
            th {{ background: #f1f5f9 !important; color: #333333 !important; }}
            td {{ color: #000000 !important; border-bottom: 1px solid #eeeeee !important; }}
            .disclaimer-banner {{
                background: #fef3c7 !important;
                color: #78350f !important;
                border-left-color: #d97706 !important;
            }}
            .ai-notice {{ color: #475569 !important; }}
            .ai-advisory-body {{ color: #1e293b !important; }}
            .section {{ page-break-inside: avoid; }}
            tr {{ page-break-inside: avoid; }}
        }}
    </style>
</head>
<body>
    <div class="report-container">
        <header class="header">
            <div class="header-title">
                <h1>{escaped_title}</h1>
                <p>{escaped_subtitle}</p>
            </div>
            <div class="meta-box">
                <div>AI-GRC Governance Platform</div>
                <div>Generated: <strong>{ts}</strong></div>
                <div>Operator: <strong>{escaped_author}</strong></div>
            </div>
        </header>

        <div class="disclaimer-banner">
            {escaped_disclaimer}
        </div>

        {f'<div class="kpi-grid">{cards_html}</div>' if cards_html else ''}

        <section class="section">
            <div class="section-badge badge-auth">[AUTHORITATIVE GRC DATA]</div>
            <h2>Authoritative Findings & Governance Inventory</h2>
            <div class="table-wrapper">
                <table>
                    <thead>
                        <tr>{headers_html}</tr>
                    </thead>
                    <tbody>
                        {rows_html if rows_html else '<tr><td colspan="' + str(len(table_headers)) + '" style="text-align:center;color:var(--text-secondary);">No records found.</td></tr>'}
                    </tbody>
                </table>
            </div>
        </section>

        {ai_section_html}

        <footer class="footer">
            <p>Confidential — Generated by AI-GRC Platform for internal authorized evaluation.</p>
            <p style="margin-top:0.25rem;">{escaped_disclaimer}</p>
        </footer>
    </div>
</body>
</html>
"""
